const padToNine = (items) => {
    const seeded = items.map((item, idx) => ({ ...item, id: idx + 1 }));
    const base = [...seeded];
    let cloneIndex = 0;
    while (seeded.length < 9 && base.length > 0) {
        const template = base[cloneIndex % base.length];
        const variantNumber = Math.floor(cloneIndex / base.length) + 1;
        seeded.push({
            ...template,
            id: seeded.length + 1,
            name: `${template.name} Variant ${variantNumber}`,
            heading: template.heading || template.name,
        });
        cloneIndex += 1;
    }
    return seeded;
};

export const furnitureData = [
    {
        category: "Bedroom",
        heading: "Bedroom Furniture",
        heroImage:
            "https://i.pinimg.com/736x/70/b7/df/70b7dfc0171383e9b1e9c6dadc059151.jpg",
        products: {
            bed: {
                title: "Luxury Beds",
                description:
                    "Premium beds crafted for comfort, elegance, and modern living.",
                items: [
                    {
                        id: 1,
                        heading: "Wooden Bed",
                        name: "Wooden King Size Bed",
                        description:
                            "Crafted from premium hardwood with a rich finish, offering durability, strength, and timeless elegance.",
                        image: "https://i.pinimg.com/1200x/d9/02/79/d902799fce03ef8f54426b45103a21e1.jpg",
                        size: ["King"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        headboard: ["Wooden"],
                        price: 1200,
                    },
                    {
                        id: 2,
                        heading: "Wooden Bed",
                        name: "Wooden King Size Bed",
                        description:
                            "Crafted from premium hardwood with a rich finish, offering durability, strength, and timeless elegance.",
                        image: "https://i.pinimg.com/1200x/d9/02/79/d902799fce03ef8f54426b45103a21e1.jpg",
                        size: ["King"],
                        material: ["Solid Wood"],
                        storage: ["Without Storage"],
                        headboard: ["Wooden"],
                        price: 2000,
                    },
                    {
                        id: 3,
                        heading: "Modern Upholstered Bed",
                        name: "Upholstered Queen Bed",
                        description:
                            "Soft fabric upholstery with plush padding, designed for maximum comfort and a contemporary bedroom look.",
                        image: "https://i.pinimg.com/1200x/ed/6b/71/ed6b712d7e90783d915c5dcdb3f621d3.jpg",
                        size: ["Queen"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        headboard: ["Upholstered"],
                        price: 950,
                    },
                    {
                        id: 4,
                        heading: "Modern Upholstered Bed",
                        name: "Upholstered King Bed",
                        description:
                            "Soft fabric upholstery with plush padding, designed for maximum comfort and a contemporary bedroom look.",
                        image: "https://i.pinimg.com/1200x/ed/6b/71/ed6b712d7e90783d915c5dcdb3f621d3.jpg",
                        size: ["King"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        headboard: ["Minimal"],
                        price: 1100,
                    },
                    {
                        id: 5,
                        heading: "Classic Wooden Bed",
                        name: "Solid Wood Single Bed",
                        description:
                            "Traditional wooden bed design with strong joinery, ideal for long-lasting everyday use.",
                        image: "https://i.pinimg.com/1200x/c8/41/55/c841557e8db02e6bc9a7aa5430edb770.jpg",
                        size: ["Single"],
                        material: ["Metal"],
                        storage: ["Without Storage"],
                        headboard: ["Wooden"],
                        price: 800,
                    },
                    {
                        id: 6,
                        heading: "Classic Wooden Bed",
                        name: "Solid Wood Queen Bed",
                        description:
                            "Traditional wooden bed design with strong joinery, ideal for long-lasting everyday use.",
                        image: "https://i.pinimg.com/1200x/c8/41/55/c841557e8db02e6bc9a7aa5430edb770.jpg",
                        size: ["Queen"],
                        material: ["Metal"],
                        storage: ["Without Storage"],
                        headboard: ["Panel"],
                        price: 900,
                    },
                    {
                        id: 7,
                        heading: "Wooden Bed",
                        name: "Wooden King Bed Deluxe",
                        description:
                            "Premium hardwood bed with extra detailing and elegant finish.",
                        image: "https://i.pinimg.com/1200x/d9/02/79/d902799fce03ef8f54426b45103a21e1.jpg",
                        size: ["King"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        headboard: ["Panel"],
                        price: 1300,
                    },
                    {
                        id: 8,
                        heading: "Wooden Bed",
                        name: "Wooden King Bed Premium",
                        description:
                            "Luxury solid wood bed with rich finish, durable and elegant for modern bedrooms.",
                        image: "https://i.pinimg.com/1200x/d9/02/79/d902799fce03ef8f54426b45103a21e1.jpg",
                        size: ["King"],
                        material: ["Solid Wood"],
                        storage: ["Without Storage"],
                        headboard: ["Wooden"],
                        price: 1500,
                    },
                    {
                        id: 9,
                        heading: "Wooden Bed",
                        name: "Wooden King Bed Supreme",
                        description:
                            "Crafted from premium hardwood for ultimate comfort and style.",
                        image: "https://i.pinimg.com/736x/b7/7c/8f/b77c8f18e1ab28eb6ed41a5dfe4fda01.jpg",
                        size: ["King"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        headboard: ["Panel"],
                        price: 1800,
                    },
                ],
            },
            wardrobe: {
                title: "Luxury Wardrobes",
                description:
                    "Premium wardrobes designed for elegance, functionality, and modern living.",
                items: [
                    {
                        id: 1,
                        heading: "Wooden Wardrobe",
                        name: "Solid Wood 3-Door Wardrobe",
                        description:
                            "Crafted from premium solid wood, offering durability and a timeless design with ample storage.",
                        image: "https://i.pinimg.com/736x/9a/68/db/9a68dbf9940e3815c759cd793eadb90d.jpg",
                        size: ["Large"],
                        material: ["Solid Wood"],
                        doors: ["3-Door"],
                        style: ["Classic"],
                        price: 1500,
                    },
                    {
                        id: 2,
                        heading: "Modern Wardrobe",
                        name: "Engineered Wood Sliding Wardrobe",
                        description:
                            "Sleek sliding door wardrobe with engineered wood finish, ideal for contemporary bedrooms.",
                        image: "https://i.pinimg.com/736x/d9/3e/cc/d93eccf31850d379510e74f2ac3b41f7.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        doors: ["Sliding"],
                        style: ["Modern"],
                        price: 1800,
                    },
                    {
                        id: 3,
                        heading: "Classic Wardrobe",
                        name: "Wooden 2-Door Wardrobe",
                        description:
                            "Traditional wooden wardrobe with sturdy construction and elegant finish for long-lasting use.",
                        image: "https://i.pinimg.com/736x/79/0d/a0/790da02d59146351018baa2de488fb5d.jpg",
                        size: ["Medium"],
                        material: ["Solid Wood"],
                        doors: ["2-Door"],
                        style: ["Classic"],
                        price: 1200,
                    },
                    {
                        id: 4,
                        heading: "Luxury Wardrobe",
                        name: "High Gloss 4-Door Wardrobe",
                        description:
                            "Premium high-gloss finish wardrobe with spacious interiors and modern design accents.",
                        image: "https://i.pinimg.com/736x/2e/d2/25/2ed225b95684f303b36231d21fc59f41.jpg",
                        size: ["Extra Large"],
                        material: ["Engineered Wood"],
                        doors: ["4-Door"],
                        style: ["Luxury"],
                        price: 2500,
                    },
                    {
                        id: 5,
                        heading: "Wardrobe with Mirror",
                        name: "Mirror Front Wooden Wardrobe",
                        description:
                            "Elegant wardrobe with full-length mirror panels and premium wood finish for style and functionality.",
                        image: "https://i.pinimg.com/1200x/df/42/19/df421919966d24007c76b9954465fa27.jpg",
                        size: ["Large"],
                        material: ["Solid Wood"],
                        doors: ["2-Door"],
                        style: ["Classic"],
                        price: 1700,
                    },
                    {
                        id: 6,
                        heading: "Modern Wardrobe",
                        name: "Sliding Door Wardrobe with Matte Finish",
                        description:
                            "Engineered wood wardrobe with smooth sliding doors and contemporary matte finish for a minimalist look.",
                        image: "https://i.pinimg.com/736x/76/7e/89/767e89468f57f6ab2735aa0550d39841.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        doors: ["Sliding"],
                        style: ["Modern"],
                        price: 1400,
                    },
                    {
                        id: 7,
                        heading: "Luxury Wooden Wardrobe",
                        name: "Solid Wood Wardrobe with Carvings",
                        description:
                            "Premium solid wood wardrobe with intricate carvings and spacious compartments for a regal look.",
                        image: "https://i.pinimg.com/736x/98/81/46/9881464d3138595ca47ea410f2bb4086.jpg",
                        size: ["Large"],
                        material: ["Solid Wood"],
                        doors: ["3-Door"],
                        style: ["Luxury"],
                        price: 2200,
                    },
                    {
                        id: 8,
                        heading: "Contemporary Wardrobe",
                        name: "Engineered Wood Wardrobe with Open Shelves",
                        description:
                            "Modern wardrobe with combination of closed storage and open shelves, perfect for display and organization.",
                        image: "https://i.pinimg.com/736x/11/23/32/112332fe39a852195725896c908f1b0e.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        doors: ["2-Door"],
                        style: ["Modern"],
                        price: 1600,
                    },
                    {
                        id: 9,
                        heading: "Classic Wooden Wardrobe",
                        name: "Solid Wood Wardrobe Deluxe",
                        description:
                            "Elegant solid wood wardrobe with deluxe detailing, spacious compartments, and premium finish.",
                        image: "https://i.pinimg.com/736x/8c/96/ce/8c96ce949bd29c781d67334639758f5a.jpg",
                        size: ["Extra Large"],
                        material: ["Solid Wood"],
                        doors: ["4-Door"],
                        style: ["Classic"],
                        price: 3000,
                    },
                ],
            },
            shelf: {
                title: "Modern Shelves",
                description:
                    "Stylish shelves to organize books, decor, and essentials in your bedroom.",
                items: padToNine([
                    {
                        heading: "Wall Mounted Shelf",
                        name: "Floating Wooden Shelf",
                        description:
                            "Minimalist floating shelf perfect for displaying decor and keeping essentials handy.",
                        image: "https://i.pinimg.com/736x/e2/7d/a5/e27da51087dedeebc32da1dd1d43b4a9.jpg",
                        size: ["Single", "Double"],
                        material: ["Solid Wood", "Engineered Wood"],
                        storage: ["Open Storage"],
                        headboard: ["Panel"],
                        price: 150,
                    },
                    {
                        heading: "Corner Shelf",
                        name: "Modern Corner Shelf",
                        description:
                            "Space-saving corner shelf with sleek design, ideal for small bedrooms.",
                        image: "https://i.pinimg.com/736x/7f/39/c8/7f39c813c64c50e30e8ac419f8889bc8.jpg",
                        size: ["Single"],
                        material: ["Metal", "Wood"],
                        storage: ["Open Storage"],
                        headboard: ["Panel"],
                        price: 180,
                    },
                    {
                        heading: "Tall Shelf",
                        name: "Ladder Style Shelf",
                        description:
                            "Leaning ladder shelf to showcase books and decor vertically.",
                        image: "https://i.pinimg.com/1200x/7a/3a/92/7a3a926a01c61eb082b8defc7104a1b2.jpg",
                        size: ["Double"],
                        material: ["Solid Wood"],
                        storage: ["Open Storage"],
                        headboard: ["Panel"],
                        price: 210,
                    },
                ]),
            },
            bedTable: {
                title: "Bedside Tables",
                description:
                    "Functional and stylish bedside tables to complement your bed.",
                items: padToNine([
                    {
                        heading: "Classic Bed Table",
                        name: "Wooden Nightstand",
                        description:
                            "Compact nightstand with drawer storage for bedside essentials.",
                        image: "https://i.pinimg.com/736x/aa/b8/0a/aab80a6db0f28cc75fd7f0438423a4f5.jpg",
                        size: ["Single"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        headboard: ["Panel"],
                        price: 200,
                    },
                    {
                        heading: "Modern Bed Table",
                        name: "Minimalist Side Table",
                        description:
                            "Sleek and minimalist side table to hold lamps, books, or decor items.",
                        image: "https://i.pinimg.com/736x/6a/e9/2d/6ae92dab5a828fad316db23468a1b374.jpg",
                        size: ["Single"],
                        material: ["Metal", "Wood"],
                        storage: ["Without Storage"],
                        headboard: ["Panel"],
                        price: 180,
                    },
                    {
                        heading: "Double Drawer Table",
                        name: "Storage Bedside Table",
                        description:
                            "Extra storage with dual drawers for organized bedside essentials.",
                        image: "https://i.pinimg.com/1200x/2e/37/9d/2e379d4e4ce474fba6b9b42a08d5167f.jpg",
                        size: ["Single"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        headboard: ["Wooden"],
                        price: 240,
                    },
                ]),
            },
            dressingTable: {
                title: "Dressing Tables",
                description:
                    "Elegant dressing tables with mirror and storage for daily grooming.",
                items: padToNine([
                    {
                        heading: "Luxury Dressing Table",
                        name: "Wooden Dressing Table with Mirror",
                        description:
                            "Spacious dressing table with drawers and a premium mirror for modern bedrooms.",
                        image: "https://i.pinimg.com/1200x/4c/82/74/4c827493700a69af3f3f9d8ca465a3b7.jpg",
                        size: ["Single"],
                        material: ["Solid Wood", "Engineered Wood"],
                        storage: ["With Storage"],
                        headboard: ["Wooden"],
                        price: 450,
                    },
                    {
                        heading: "Compact Dressing Table",
                        name: "Minimalist Vanity Table",
                        description:
                            "Compact dressing table ideal for small bedrooms with sleek storage.",
                        image: "https://i.pinimg.com/736x/a5/47/14/a54714c4f1340178ede1d5222a2bfd3c.jpg",
                        size: ["Single"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        headboard: ["Wooden"],
                        price: 350,
                    },
                    {
                        heading: "Round Mirror Vanity",
                        name: "Scandi Vanity Table",
                        description:
                            "Light wood vanity with round mirror and slim storage drawers.",
                        image: "https://i.pinimg.com/736x/30/af/47/30af477ce724abd62c349dc82c4fd7ac.jpg",
                        size: ["Single"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        headboard: ["Wooden"],
                        price: 380,
                    },
                ]),
            },
            bedroomCouch: {
                title: "Bedroom Couches",
                description: "Comfortable bedroom couches for lounging and relaxation.",
                items: padToNine([
                    {
                        heading: "Fabric Couch",
                        name: "Modern Single Sofa",
                        description:
                            "Compact single-seater sofa with plush fabric for bedroom comfort.",
                        image: "https://i.pinimg.com/1200x/b7/2f/e6/b72fe6b07b8b0d0b32844e79717df3ee.jpg",
                        size: ["Single"],
                        material: ["Fabric", "Wood"],
                        storage: ["Without Storage"],
                        headboard: ["Wooden"],
                        price: 400,
                    },
                    {
                        heading: "Leather Couch",
                        name: "Premium Bedroom Sofa",
                        description:
                            "Stylish leather sofa for your bedroom, combining luxury with comfort.",
                        image: "https://i.pinimg.com/1200x/62/36/80/623680f591b24a80132341ef3cd13c1b.jpg",
                        size: ["Single", "Double"],
                        material: ["Leather", "Metal"],
                        storage: ["Without Storage"],
                        headboard: ["Wooden"],
                        price: 650,
                    },
                    {
                        heading: "Tufted Couch",
                        name: "Chesterfield Bedroom Sofa",
                        description:
                            "Tufted fabric couch that adds a classic touch to the bedroom.",
                        image: "https://i.pinimg.com/1200x/62/36/80/623680f591b24a80132341ef3cd13c1b.jpg",
                        size: ["Double"],
                        material: ["Fabric", "Wood"],
                        storage: ["Without Storage"],
                        headboard: ["Wooden"],
                        price: 720,
                    },
                ]),
            },
        },
    },

    {
        category: "Living",
        heading: "Living Room Furniture",
        heroImage:
            "https://i.pinimg.com/1200x/51/ef/3f/51ef3f9ea4128abcf79a3e8a62144957.jpg",
        products: {
            sofa: {
                title: "Luxury Sofas",
                description:
                    "Comfort-driven sofas crafted for statement living spaces.",
                items: padToNine([
                    {
                        heading: "Modern Sofa",
                        name: "3-Seater Fabric Sofa",
                        description: "Plush fabric sofa with deep seating and sleek legs.",
                        image: "https://i.pinimg.com/1200x/af/bd/cf/afbdcf71db5b292e7f58d84ba6bc407d.jpg",
                        seating: ["3-Seater"],
                        material: ["Fabric", "Metal"],
                        storage: ["Without Storage"],
                        style: ["Modern"],
                        price: 1200,
                    },
                    {
                        heading: "Classic Sofa",
                        name: "Rolled Arm Sofa",
                        description: "Timeless rolled arms with supportive cushions.",
                        image: "https://i.pinimg.com/1200x/a9/09/37/a909376014e837f1d30ba0201e295193.jpg",
                        seating: ["3-Seater"],
                        material: ["Fabric", "Wood"],
                        storage: ["Without Storage"],
                        style: ["Classic"],
                        price: 1350,
                    },
                    {
                        heading: "Sectional",
                        name: "L-Shaped Sectional",
                        description: "Spacious sectional with chaise for lounging.",
                        image: "https://i.pinimg.com/736x/4f/7f/5d/4f7f5d5538a30b604c742ffa0ccc5147.jpg",
                        seating: ["4-Seater"],
                        material: ["Fabric", "Wood"],
                        storage: ["With Storage"],
                        style: ["Modern"],
                        price: 1800,
                    },
                ]),
            },
            tvunit: {
                title: "TV Units",
                description: "Media units with smart cable management and storage.",
                items: padToNine([
                    {
                        heading: "Floating Unit",
                        name: "Wall Mounted TV Unit",
                        description: "Clean-lined floating TV console with open shelves.",
                        image: "https://i.pinimg.com/736x/09/2d/d0/092dd08a04be3e31bdebed561e798447.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        style: ["Modern"],
                        price: 600,
                    },
                    {
                        heading: "Low Unit",
                        name: "Scandi TV Console",
                        description: "Low-profile console with sliding doors.",
                        image: "https://i.pinimg.com/736x/99/04/81/99048189af5e75574815fa3791cda778.jpg",
                        size: ["Large"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        style: ["Scandi"],
                        price: 720,
                    },
                    {
                        heading: "High Storage Unit",
                        name: "Tall Media Unit",
                        description: "Tall media unit with drawers and display shelves.",
                        image: "https://i.pinimg.com/1200x/e4/bf/0d/e4bf0d153891129dd98aa01142dc4e25.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        style: ["Modern"],
                        price: 780,
                    },
                ]),
            },
            centraltable: {
                title: "Central Tables",
                description: "Statement coffee tables for living rooms.",
                items: padToNine([
                    {
                        heading: "Glass Top",
                        name: "Glass Coffee Table",
                        description: "Tempered glass top with metal frame.",
                        image: "https://i.pinimg.com/1200x/e4/bf/0d/e4bf0d153891129dd98aa01142dc4e25.jpg",
                        shape: ["Rectangle"],
                        material: ["Glass", "Metal"],
                        storage: ["Without Storage"],
                        price: 320,
                    },
                    {
                        heading: "Wood Top",
                        name: "Oak Coffee Table",
                        description: "Solid oak table with lower shelf storage.",
                        image: "https://i.pinimg.com/736x/ee/99/7e/ee997ed3288a0ece3b7115e23ea9efd3.jpg",
                        shape: ["Rectangle"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        price: 380,
                    },
                    {
                        heading: "Round Table",
                        name: "Round Walnut Table",
                        description: "Round table with warm walnut finish.",
                        image: "https://i.pinimg.com/1200x/09/2d/d0/092dd08a04be3e31bdebed561e798447.jpg",
                        shape: ["Round"],
                        material: ["Engineered Wood"],
                        storage: ["Without Storage"],
                        price: 340,
                    },
                ]),
            },
            chair: {
                title: "Designer Chairs",
                description:
                    "Comfortable and stylish chairs designed to enhance modern living spaces.",
                items: padToNine([
                    {
                        heading: "Accent Chair",
                        name: "Modern Accent Chair",
                        description:
                            "A statement accent chair with ergonomic comfort and premium upholstery.",
                        image:
                            "https://i.pinimg.com/1200x/00/71/11/0071110882356dcfe138a82494212e1f.jpg",
                        size: ["Single"],
                        material: ["Metal", "Engineered Wood"],
                        storage: ["Without Storage"],
                        headboard: ["Minimal"],
                        price: 350,
                    },
                    {
                        heading: "Lounge Chair",
                        name: "Luxury Lounge Chair",
                        description:
                            "Relax in style with this plush lounge chair designed for comfort and elegance.",
                        image:
                            "https://i.pinimg.com/1200x/4c/f0/4e/4cf04e6511e319de03de6660b1b8f408.jpg",
                        size: ["Single"],
                        material: ["Solid Wood", "Metal"],
                        storage: ["Without Storage"],
                        headboard: ["Upholstered"],
                        price: 500,
                    },
                    {
                        heading: "Wing Chair",
                        name: "High Back Wing Chair",
                        description: "High-back chair with winged sides for cozy seating.",
                        image: "https://i.pinimg.com/736x/4b/50/6a/4b506ab7424c5ad9e8ea0cc38643c14a.jpg",
                        size: ["Single"],
                        material: ["Fabric", "Wood"],
                        storage: ["Without Storage"],
                        headboard: ["Minimal"],
                        price: 420,
                    },
                ]),
            },
            sidetable: {
                title: "Side Tables",
                description: "Compact side tables to pair with sofas and chairs.",
                items: padToNine([
                    {
                        heading: "Round Side",
                        name: "Round Metal Side Table",
                        description: "Slim round table with powder-coated frame.",
                        image: "https://i.pinimg.com/736x/99/04/81/99048189af5e75574815fa3791cda778.jpg",
                        shape: ["Round"],
                        material: ["Metal"],
                        storage: ["Without Storage"],
                        price: 180,
                    },
                    {
                        heading: "Square Side",
                        name: "Solid Wood Side Table",
                        description: "Square side table with small drawer.",
                        image: "https://i.pinimg.com/736x/ee/99/7e/ee997ed3288a0ece3b7115e23ea9efd3.jpg",
                        shape: ["Square"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        price: 210,
                    },
                    {
                        heading: "Nested Tables",
                        name: "Nest of Tables",
                        description: "Set of two nesting tables for flexible use.",
                        image: "https://i.pinimg.com/1200x/09/2d/d0/092dd08a04be3e31bdebed561e798447.jpg",
                        shape: ["Rectangle"],
                        material: ["Engineered Wood"],
                        storage: ["Without Storage"],
                        price: 240,
                    },
                ]),
            },
            reclinersofa: {
                title: "Recliner Sofas",
                description:
                    "Reclining comfort for movie nights and all-day lounging.",
                items: padToNine([
                    {
                        heading: "Manual Recliner",
                        name: "3-Seater Recliner Sofa",
                        description: "Manual reclining sofa with plush cushions.",
                        image: "https://i.pinimg.com/1200x/a9/09/37/a909376014e837f1d30ba0201e295193.jpg",
                        seating: ["3-Seater"],
                        material: ["Fabric", "Metal"],
                        storage: ["Without Storage"],
                        style: ["Modern"],
                        price: 1700,
                    },
                    {
                        heading: "Power Recliner",
                        name: "Power Reclining Sofa",
                        description: "Powered recline with USB charging ports.",
                        image: "https://i.pinimg.com/736x/4f/7f/5d/4f7f5d5538a30b604c742ffa0ccc5147.jpg",
                        seating: ["3-Seater"],
                        material: ["Leather", "Metal"],
                        storage: ["Without Storage"],
                        style: ["Modern"],
                        price: 2100,
                    },
                    {
                        heading: "Home Theatre",
                        name: "Recliner With Console",
                        description: "Center console with cup holders and storage.",
                        image: "https://i.pinimg.com/1200x/af/bd/cf/afbdcf71db5b292e7f58d84ba6bc407d.jpg",
                        seating: ["2-Seater"],
                        material: ["Leather", "Metal"],
                        storage: ["With Storage"],
                        style: ["Modern"],
                        price: 1900,
                    },
                ]),
            },
        },
    },

    {
        category: "Study",
        heading: "Study Furniture",
        heroImage:
            "https://i.pinimg.com/1200x/d5/fb/23/d5fb23f8a9a02376da29570e9d70157a.jpg",
        products: {
            studytable: {
                title: "Study Tables",
                description: "Ergonomic desks for focused work.",
                items: padToNine([
                    {
                        heading: "Compact Desk",
                        name: "Single Drawer Desk",
                        description: "Space-saving desk with drawer and cable pass-through.",
                        image: "https://i.pinimg.com/1200x/d5/fb/23/d5fb23f8a9a02376da29570e9d70157a.jpg",
                        size: ["Single"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 320,
                    },
                    {
                        heading: "Executive Desk",
                        name: "Wide Work Desk",
                        description: "Wide surface with dual drawers for storage.",
                        image: "https://i.pinimg.com/736x/fa/8f/0f/fa8f0f9c983630fdf5240b50d980592d.jpg",
                        size: ["Large"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        price: 480,
                    },
                    {
                        heading: "Standing Desk",
                        name: "Height Adjustable Desk",
                        description: "Adjustable height desk for sit-stand setups.",
                        image: "https://i.pinimg.com/736x/85/b7/42/85b742544e7760cd9a5c89c60cd54bf8.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood", "Metal"],
                        storage: ["Without Storage"],
                        price: 520,
                    },
                ]),
            },
            studychair: {
                title: "Study Chairs",
                description: "Ergonomic chairs for long working hours.",
                items: padToNine([
                    {
                        heading: "Mesh Chair",
                        name: "Ergonomic Mesh Chair",
                        description: "Breathable mesh back with lumbar support.",
                        image: "https://i.pinimg.com/736x/54/bd/35/54bd35417ae8d3b9f11113daf38695af.jpg",
                        size: ["Single"],
                        material: ["Mesh", "Metal"],
                        storage: ["Without Storage"],
                        price: 220,
                    },
                    {
                        heading: "Executive Chair",
                        name: "Leatherette Chair",
                        description: "Padded seat with tilt and height adjustment.",
                        image: "https://i.pinimg.com/736x/05/d8/fc/05d8fc8137835ca3ec07dce887357f20.jpg",
                        size: ["Single"],
                        material: ["Leatherette", "Metal"],
                        storage: ["Without Storage"],
                        price: 260,
                    },
                    {
                        heading: "Task Chair",
                        name: "Minimal Task Chair",
                        description: "Compact task chair for small desks.",
                        image: "https://i.pinimg.com/736x/05/d8/fc/05d8fc8137835ca3ec07dce887357f20.jpg",
                        size: ["Single"],
                        material: ["Fabric", "Metal"],
                        storage: ["Without Storage"],
                        price: 180,
                    },
                ]),
            },
            rackshelf: {
                title: "Rack Shelves",
                description: "Open rack shelves for books and files.",
                items: padToNine([
                    {
                        heading: "Metal Rack",
                        name: "Industrial Rack Shelf",
                        description: "Metal frame with wooden shelves.",
                        image: "https://i.pinimg.com/736x/10/9b/02/109b02298f4ca5718476c4ff2e95f67c.jpg",
                        size: ["Large"],
                        material: ["Metal", "Wood"],
                        storage: ["Open Storage"],
                        price: 260,
                    },
                    {
                        heading: "5-Tier Rack",
                        name: "Tall Book Rack",
                        description: "Five-tier rack for books and decor.",
                        image: "https://i.pinimg.com/1200x/15/59/f9/1559f90eab63e6d6eaddce2010163952.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        storage: ["Open Storage"],
                        price: 240,
                    },
                    {
                        heading: "Compact Rack",
                        name: "3-Tier Study Rack",
                        description: "Compact rack for small study setups.",
                        image: "https://i.pinimg.com/736x/52/38/2d/52382d0ef3e257a9d27df38df1d06795.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["Open Storage"],
                        price: 190,
                    },
                ]),
            },
            revolvingchair: {
                title: "Revolving Chairs",
                description: "Swivel chairs with smooth movement.",
                items: padToNine([
                    {
                        heading: "Ergo Swivel",
                        name: "Ergo Swivel Chair",
                        description: "Breathable mesh swivel chair with wheels.",
                        image: "https://i.pinimg.com/736x/85/b7/42/85b742544e7760cd9a5c89c60cd54bf8.jpg",
                        size: ["Single"],
                        material: ["Mesh", "Metal"],
                        storage: ["Without Storage"],
                        price: 240,
                    },
                    {
                        heading: "Cushion Swivel",
                        name: "Padded Swivel Chair",
                        description: "Cushioned seat with 360 swivel.",
                        image: "https://i.pinimg.com/736x/fa/8f/0f/fa8f0f9c983630fdf5240b50d980592d.jpg",
                        size: ["Single"],
                        material: ["Fabric", "Metal"],
                        storage: ["Without Storage"],
                        price: 230,
                    },
                    {
                        heading: "Executive Swivel",
                        name: "Executive Swivel",
                        description: "Tall back swivel with tilt tension.",
                        image: "https://i.pinimg.com/736x/ea/9a/21/ea9a21ba60809ebf869fa7657dca4f75.jpg",
                        size: ["Single"],
                        material: ["Leatherette", "Metal"],
                        storage: ["Without Storage"],
                        price: 280,
                    },
                ]),
            },
            shelvesunit: {
                title: "Shelves Units",
                description: "Closed and open storage combinations.",
                items: padToNine([
                    {
                        heading: "Display Unit",
                        name: "Glass Door Shelf Unit",
                        description: "Display unit with glass doors and open shelves.",
                        image: "https://i.pinimg.com/736x/10/9b/02/109b02298f4ca5718476c4ff2e95f67c.jpg",
                        size: ["Large"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        price: 420,
                    },
                    {
                        heading: "Closed Unit",
                        name: "Cabinet Shelf Unit",
                        description: "Combination of cabinets and shelves.",
                        image: "https://i.pinimg.com/1200x/52/38/2d/52382d0ef3e257a9d27df38df1d06795.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 360,
                    },
                    {
                        heading: "Minimal Unit",
                        name: "Open Shelf Tower",
                        description: "Open shelf tower for books and decor.",
                        image: "https://i.pinimg.com/1200x/15/59/f9/1559f90eab63e6d6eaddce2010163952.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["Open Storage"],
                        price: 260,
                    },
                ]),
            },
            studybedtable: {
                title: "Study Bed Tables",
                description: "Bed tables for reading and work in bed.",
                items: padToNine([
                    {
                        heading: "Foldable Bed Table",
                        name: "Foldable Laptop Table",
                        description: "Foldable laptop table with cup holder.",
                        image: "https://i.pinimg.com/1200x/52/38/2d/52382d0ef3e257a9d27df38df1d06795.jpg",
                        size: ["Single"],
                        material: ["Engineered Wood"],
                        storage: ["Without Storage"],
                        price: 90,
                    },
                    {
                        heading: "Adjustable Bed Table",
                        name: "Adjustable Height Bed Table",
                        description: "Adjustable height for reading and working.",
                        image: "https://i.pinimg.com/1200x/15/59/f9/1559f90eab63e6d6eaddce2010163952.jpg",
                        size: ["Single"],
                        material: ["Solid Wood"],
                        storage: ["Without Storage"],
                        price: 110,
                    },
                    {
                        heading: "Padded Bed Table",
                        name: "Cushioned Bed Table",
                        description: "Soft base for comfortable lap use.",
                        image: "https://i.pinimg.com/736x/10/9b/02/109b02298f4ca5718476c4ff2e95f67c.jpg",
                        size: ["Single"],
                        material: ["Engineered Wood"],
                        storage: ["Without Storage"],
                        price: 100,
                    },
                ]),
            },
        },
    },

    {
        category: "Bathroom",
        heading: "Bathroom Furniture",
        heroImage:
            "https://i.pinimg.com/1200x/8b/49/25/8b49255acfa55b3177ceb58a7d728e62.jpg",
        products: {
            vanity: {
                title: "Vanity Units",
                description: "Elegant vanities with ample storage.",
                items: padToNine([
                    {
                        heading: "Wall Mount Vanity",
                        name: "Floating Vanity",
                        description: "Floating vanity with soft-close drawers.",
                        image: "https://i.pinimg.com/1200x/8b/49/25/8b49255acfa55b3177ceb58a7d728e62.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        style: ["Modern"],
                        price: 520,
                    },
                    {
                        heading: "Double Vanity",
                        name: "Double Sink Vanity",
                        description: "Spacious double sink vanity for large bathrooms.",
                        image: "https://i.pinimg.com/736x/69/ea/ff/69eaff512bfab7a9497cd9f5008a92f0.jpg",
                        size: ["Large"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        style: ["Classic"],
                        price: 880,
                    },
                    {
                        heading: "Compact Vanity",
                        name: "Small Vanity Unit",
                        description: "Compact vanity for small spaces.",
                        image: "https://i.pinimg.com/736x/97/30/24/9730248ee967ffebec999867580bd76b.jpg",
                        size: ["Small"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        style: ["Modern"],
                        price: 420,
                    },
                ]),
            },
            mirrorcabinet: {
                title: "Mirror Cabinets",
                description: "Storage with mirrors for everyday essentials.",
                items: padToNine([
                    {
                        heading: "Slim Mirror Cabinet",
                        name: "Slim Wall Cabinet",
                        description: "Slim mirrored cabinet with shelves.",
                        image: "https://i.pinimg.com/1200x/fa/31/1d/fa311dcf664e3df5cc4bfa4bfb307879.jpg",
                        size: ["Small"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 210,
                    },
                    {
                        heading: "Wide Mirror Cabinet",
                        name: "Wide Mirror Cabinet",
                        description: "Wide cabinet with dual mirror doors.",
                        image: "https://i.pinimg.com/736x/97/30/24/9730248ee967ffebec999867580bd76b.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 260,
                    },
                    {
                        heading: "Tall Mirror Cabinet",
                        name: "Tall Mirrored Storage",
                        description: "Tall cabinet for extra vertical storage.",
                        image: "https://i.pinimg.com/736x/69/ea/ff/69eaff512bfab7a9497cd9f5008a92f0.jpg",
                        size: ["Large"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        price: 320,
                    },
                ]),
            },
            undersink: {
                title: "Under Sink Cabinets",
                description: "Organized storage beneath the sink.",
                items: padToNine([
                    {
                        heading: "Compact Under Sink",
                        name: "Two Door Under Sink",
                        description: "Two door cabinet for under-sink storage.",
                        image: "https://i.pinimg.com/736x/69/ea/ff/69eaff512bfab7a9497cd9f5008a92f0.jpg",
                        size: ["Small"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 240,
                    },
                    {
                        heading: "Drawer Under Sink",
                        name: "Drawer Under Sink",
                        description: "Drawer + door combo for flexible storage.",
                        image: "https://i.pinimg.com/736x/97/30/24/9730248ee967ffebec999867580bd76b.jpg",
                        size: ["Medium"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        price: 280,
                    },
                    {
                        heading: "Open Shelf Under Sink",
                        name: "Open Shelf Under Sink",
                        description: "Open shelf style for easy access.",
                        image: "https://i.pinimg.com/1200x/4a/17/72/4a17728f1e2bf942dfcafa8205d87cd3.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["Open Storage"],
                        price: 220,
                    },
                ]),
            },
            bathroomshelves: {
                title: "Bathroom Shelves",
                description: "Wall shelves for toiletries and decor.",
                items: padToNine([
                    {
                        heading: "Floating Bathroom Shelf",
                        name: "Floating Shelf Set",
                        description: "Set of two floating shelves.",
                        image: "https://i.pinimg.com/736x/97/30/24/9730248ee967ffebec999867580bd76b.jpg",
                        size: ["Small"],
                        material: ["Engineered Wood"],
                        storage: ["Open Storage"],
                        price: 110,
                    },
                    {
                        heading: "Corner Bathroom Shelf",
                        name: "Corner Shelf Trio",
                        description: "Three-tier corner shelf.",
                        image: "https://i.pinimg.com/1200x/4a/17/72/4a17728f1e2bf942dfcafa8205d87cd3.jpg",
                        size: ["Small"],
                        material: ["Metal"],
                        storage: ["Open Storage"],
                        price: 95,
                    },
                    {
                        heading: "Glass Shelf",
                        name: "Glass Bathroom Shelf",
                        description: "Tempered glass wall shelf.",
                        image: "https://i.pinimg.com/736x/69/ea/ff/69eaff512bfab7a9497cd9f5008a92f0.jpg",
                        size: ["Small"],
                        material: ["Glass", "Metal"],
                        storage: ["Open Storage"],
                        price: 130,
                    },
                ]),
            },
            laundrycabinet: {
                title: "Laundry Cabinets",
                description: "Utility cabinets for laundry spaces.",
                items: padToNine([
                    {
                        heading: "Tall Laundry Cabinet",
                        name: "Tall Utility Cabinet",
                        description: "Tall cabinet with hamper and shelves.",
                        image: "https://i.pinimg.com/1200x/4a/17/72/4a17728f1e2bf942dfcafa8205d87cd3.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 260,
                    },
                    {
                        heading: "Rolling Laundry Cabinet",
                        name: "Rolling Laundry Cart",
                        description: "Mobile cabinet with baskets.",
                        image: "https://i.pinimg.com/736x/97/30/24/9730248ee967ffebec999867580bd76b.jpg",
                        size: ["Medium"],
                        material: ["Metal"],
                        storage: ["With Storage"],
                        price: 190,
                    },
                    {
                        heading: "Laundry Shelf Unit",
                        name: "Laundry Shelf",
                        description: "Shelf for detergent and baskets.",
                        image: "https://i.pinimg.com/736x/69/ea/ff/69eaff512bfab7a9497cd9f5008a92f0.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["Open Storage"],
                        price: 170,
                    },
                ]),
            },
            bathroomstool: {
                title: "Bathroom Stools",
                description: "Compact stools for bathroom seating.",
                items: padToNine([
                    {
                        heading: "Wooden Stool",
                        name: "Teak Shower Stool",
                        description: "Water-resistant teak shower stool.",
                        image: "https://i.pinimg.com/1200x/cb/ea/72/cbea72531922c10f7e1c1d3f554f253a.jpg",
                        size: ["Single"],
                        material: ["Teak"],
                        storage: ["Without Storage"],
                        price: 120,
                    },
                    {
                        heading: "Bamboo Stool",
                        name: "Bamboo Bathroom Stool",
                        description: "Lightweight bamboo stool.",
                        image: "https://i.pinimg.com/736x/97/30/24/9730248ee967ffebec999867580bd76b.jpg",
                        size: ["Single"],
                        material: ["Bamboo"],
                        storage: ["Without Storage"],
                        price: 90,
                    },
                    {
                        heading: "Plastic Stool",
                        name: "Anti-Slip Stool",
                        description: "Anti-slip stool for daily use.",
                        image: "https://i.pinimg.com/736x/69/ea/ff/69eaff512bfab7a9497cd9f5008a92f0.jpg",
                        size: ["Single"],
                        material: ["Plastic"],
                        storage: ["Without Storage"],
                        price: 60,
                    },
                ]),
            },
        },
    },

    {
        category: "Garden",
        heading: "Garden Furniture",
        heroImage:
            "https://i.pinimg.com/1200x/38/46/bc/3846bc52ece40f7926c1e3a8be68caea.jpg",
        products: {
            outdoorsofa: {
                title: "Outdoor Sofas",
                description: "Weather-ready sofas for outdoor lounging.",
                items: padToNine([
                    {
                        heading: "Rattan Sofa",
                        name: "Rattan Outdoor Sofa",
                        description: "Handwoven rattan-look sofa with cushions.",
                        image: "https://i.pinimg.com/1200x/38/46/bc/3846bc52ece40f7926c1e3a8be68caea.jpg",
                        seating: ["3-Seater"],
                        material: ["Rattan", "Metal"],
                        storage: ["Without Storage"],
                        price: 750,
                    },
                    {
                        heading: "Aluminium Sofa",
                        name: "Aluminium Patio Sofa",
                        description: "Powder-coated aluminium frame with quick-dry cushions.",
                        image: "https://i.pinimg.com/1200x/4c/f0/4e/4cf04e6511e319de03de6660b1b8f408.jpg",
                        seating: ["3-Seater"],
                        material: ["Aluminium", "Fabric"],
                        storage: ["Without Storage"],
                        price: 820,
                    },
                    {
                        heading: "Wooden Outdoor Sofa",
                        name: "Teak Outdoor Sofa",
                        description: "Teak frame sofa with weather-resistant cushions.",
                        image: "https://i.pinimg.com/736x/44/cc/54/44cc5436b127c49f608bf734b7472b47.jpg",
                        seating: ["2-Seater"],
                        material: ["Teak", "Fabric"],
                        storage: ["Without Storage"],
                        price: 880,
                    },
                ]),
            },
            gardendining: {
                title: "Garden Dining Sets",
                description: "Dining sets designed for the outdoors.",
                items: padToNine([
                    {
                        heading: "6-Seater Set",
                        name: "Rattan Dining Set",
                        description: "Rattan-look dining set with glass top table.",
                        image: "https://i.pinimg.com/1200x/57/38/59/5738598db637bc052f234ad55c67590c.jpg",
                        seating: ["6-Seater"],
                        material: ["Rattan", "Glass"],
                        storage: ["Without Storage"],
                        price: 980,
                    },
                    {
                        heading: "4-Seater Set",
                        name: "Compact Dining Set",
                        description: "Compact aluminium dining set.",
                        image: "https://i.pinimg.com/736x/4b/50/6a/4b506ab7424c5ad9e8ea0cc38643c14a.jpg",
                        seating: ["4-Seater"],
                        material: ["Aluminium", "Glass"],
                        storage: ["Without Storage"],
                        price: 780,
                    },
                    {
                        heading: "Wood Dining Set",
                        name: "Teak Dining Set",
                        description: "Teak table with matching chairs.",
                        image: "https://i.pinimg.com/1200x/38/46/bc/3846bc52ece40f7926c1e3a8be68caea.jpg",
                        seating: ["6-Seater"],
                        material: ["Teak"],
                        storage: ["Without Storage"],
                        price: 1050,
                    },
                ]),
            },
            loungechair: {
                title: "Lounge Chairs",
                description: "Relaxed lounge chairs for patios.",
                items: padToNine([
                    {
                        heading: "Reclining Lounge",
                        name: "Reclining Lounge Chair",
                        description: "Adjustable back lounge chair.",
                        image: "https://i.pinimg.com/1200x/4c/f0/4e/4cf04e6511e319de03de6660b1b8f408.jpg",
                        size: ["Single"],
                        material: ["Aluminium", "Fabric"],
                        storage: ["Without Storage"],
                        price: 240,
                    },
                    {
                        heading: "Foldable Lounge",
                        name: "Foldable Lounger",
                        description: "Foldable and portable lounge chair.",
                        image: "https://i.pinimg.com/1200x/4c/f0/4e/4cf04e6511e319de03de6660b1b8f408.jpg",
                        size: ["Single"],
                        material: ["Metal", "Fabric"],
                        storage: ["Without Storage"],
                        price: 180,
                    },
                    {
                        heading: "Wooden Lounge",
                        name: "Wooden Lounge Chair",
                        description: "Classic wooden lounge chair with cushion.",
                        image: "https://i.pinimg.com/736x/44/cc/54/44cc5436b127c49f608bf734b7472b47.jpg",
                        size: ["Single"],
                        material: ["Teak", "Fabric"],
                        storage: ["Without Storage"],
                        price: 260,
                    },
                ]),
            },
            gardentable: {
                title: "Garden Tables",
                description: "Outdoor tables for gatherings.",
                items: padToNine([
                    {
                        heading: "Round Garden Table",
                        name: "Round Bistro Table",
                        description: "Compact round bistro table.",
                        image: "https://i.pinimg.com/736x/ee/99/7e/ee997ed3288a0ece3b7115e23ea9efd3.jpg",
                        shape: ["Round"],
                        material: ["Metal"],
                        storage: ["Without Storage"],
                        price: 180,
                    },
                    {
                        heading: "Rectangular Garden Table",
                        name: "Family Garden Table",
                        description: "Rectangular table for family dining.",
                        image: "https://i.pinimg.com/1200x/38/46/bc/3846bc52ece40f7926c1e3a8be68caea.jpg",
                        shape: ["Rectangle"],
                        material: ["Teak"],
                        storage: ["Without Storage"],
                        price: 320,
                    },
                    {
                        heading: "Folding Garden Table",
                        name: "Foldable Table",
                        description: "Foldable table for easy storage.",
                        image: "https://i.pinimg.com/736x/4b/50/6a/4b506ab7424c5ad9e8ea0cc38643c14a.jpg",
                        shape: ["Rectangle"],
                        material: ["Aluminium"],
                        storage: ["Without Storage"],
                        price: 210,
                    },
                ]),
            },
            sunlounger: {
                title: "Sun Loungers",
                description: "Loungers for poolside relaxation.",
                items: padToNine([
                    {
                        heading: "Pool Lounger",
                        name: "Reclining Pool Lounger",
                        description: "Reclining lounger with breathable fabric.",
                        image: "https://i.pinimg.com/736x/44/cc/54/44cc5436b127c49f608bf734b7472b47.jpg",
                        size: ["Single"],
                        material: ["Aluminium", "Fabric"],
                        storage: ["Without Storage"],
                        price: 260,
                    },
                    {
                        heading: "Wood Sunbed",
                        name: "Teak Sunbed",
                        description: "Adjustable teak sunbed.",
                        image: "https://i.pinimg.com/736x/44/cc/54/44cc5436b127c49f608bf734b7472b47.jpg",
                        size: ["Single"],
                        material: ["Teak", "Fabric"],
                        storage: ["Without Storage"],
                        price: 320,
                    },
                    {
                        heading: "Foldable Sunbed",
                        name: "Foldable Sunbed",
                        description: "Foldable sunbed for easy storage.",
                        image: "https://i.pinimg.com/1200x/38/46/bc/3846bc52ece40f7926c1e3a8be68caea.jpg",
                        size: ["Single"],
                        material: ["Metal", "Fabric"],
                        storage: ["Without Storage"],
                        price: 210,
                    },
                ]),
            },
            gardenbench: {
                title: "Garden Benches",
                description: "Benches for patios and lawns.",
                items: padToNine([
                    {
                        heading: "Wood Bench",
                        name: "Classic Garden Bench",
                        description: "Classic wooden garden bench.",
                        image: "https://i.pinimg.com/736x/4b/50/6a/4b506ab7424c5ad9e8ea0cc38643c14a.jpg",
                        seating: ["2-Seater"],
                        material: ["Teak"],
                        storage: ["Without Storage"],
                        price: 260,
                    },
                    {
                        heading: "Metal Bench",
                        name: "Metal Park Bench",
                        description: "Durable metal park-style bench.",
                        image: "https://i.pinimg.com/736x/4b/50/6a/4b506ab7424c5ad9e8ea0cc38643c14a.jpg",
                        seating: ["3-Seater"],
                        material: ["Metal"],
                        storage: ["Without Storage"],
                        price: 230,
                    },
                    {
                        heading: "Storage Bench",
                        name: "Bench with Storage",
                        description: "Bench with built-in storage compartment.",
                        image: "https://i.pinimg.com/1200x/38/46/bc/3846bc52ece40f7926c1e3a8be68caea.jpg",
                        seating: ["2-Seater"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 290,
                    },
                ]),
            },
        },
    },

    {
        category: "Kitchen",
        heading: "Kitchen Furniture",
        heroImage:
            "https://i.pinimg.com/1200x/03/29/cc/0329cc61e86bab86f44cf9170fe5373d.jpg",
        products: {
            kitchencabinet: {
                title: "Modular Kitchen Cabinets",
                description:
                    "Smart storage solutions crafted for efficient and stylish modern kitchens.",
                items: padToNine([
                    {
                        heading: "Gloss Finish Cabinet",
                        name: "High Gloss Kitchen Cabinet",
                        description:
                            "Smooth high-gloss finish cabinets that offer a modern, clean, and spacious kitchen appearance.",
                        image:
                            "https://i.pinimg.com/1200x/03/29/cc/0329cc61e86bab86f44cf9170fe5373d.jpg",
                        size: ["Single", "Queen"],
                        material: ["Engineered Wood", "Metal"],
                        storage: ["With Storage"],
                        headboard: ["Minimal"],
                        price: 600,
                    },
                    {
                        heading: "Wood Finish Cabinet",
                        name: "Wood Texture Cabinet",
                        description:
                            "Natural wood-textured cabinets that blend warmth with modern modular kitchen design.",
                        image:
                            "https://i.pinimg.com/1200x/76/dc/2e/76dc2ee8a650106fea2354ccb2beacc0.jpg",
                        size: ["Queen", "King"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        headboard: ["Panel"],
                        price: 800,
                    },
                    {
                        heading: "Matte Finish Cabinet",
                        name: "Matte Kitchen Cabinet",
                        description: "Matte finish cabinets with soft-close hinges.",
                        image:
                            "https://i.pinimg.com/736x/d8/98/02/d89802713e231b4ea221148b0f92ff3d.jpg",
                        size: ["Queen"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        headboard: ["Minimal"],
                        price: 700,
                    },
                ]),
            },
            kitchenisland: {
                title: "Kitchen Islands",
                description: "Islands for prep, dining, and storage.",
                items: padToNine([
                    {
                        heading: "Storage Island",
                        name: "Island with Drawers",
                        description: "Island with drawers and breakfast overhang.",
                        image: "https://i.pinimg.com/1200x/71/bb/cb/71bbcb9c8561f9c9ad34dbe68982d67a.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 920,
                    },
                    {
                        heading: "Butcher Block Island",
                        name: "Butcher Block Island",
                        description: "Wood top island for heavy prep.",
                        image: "https://i.pinimg.com/1200x/03/29/cc/0329cc61e86bab86f44cf9170fe5373d.jpg",
                        size: ["Medium"],
                        material: ["Solid Wood"],
                        storage: ["With Storage"],
                        price: 860,
                    },
                    {
                        heading: "Mobile Island",
                        name: "Rolling Kitchen Island",
                        description: "Mobile island with locking casters.",
                        image: "https://i.pinimg.com/1200x/76/dc/2e/76dc2ee8a650106fea2354ccb2beacc0.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 720,
                    },
                ]),
            },
            barstool: {
                title: "Bar Stools",
                description: "Stools for island and bar counters.",
                items: padToNine([
                    {
                        heading: "Upholstered Stool",
                        name: "Upholstered Bar Stool",
                        description: "Padded bar stool with footrest.",
                        image: "https://i.pinimg.com/1200x/32/01/00/3201002dff24003ec351f9879251556b.jpg",
                        size: ["Single"],
                        material: ["Fabric", "Metal"],
                        storage: ["Without Storage"],
                        price: 150,
                    },
                    {
                        heading: "Wood Stool",
                        name: "Solid Wood Bar Stool",
                        description: "Solid wood stool with backrest.",
                        image: "https://i.pinimg.com/1200x/71/bb/cb/71bbcb9c8561f9c9ad34dbe68982d67a.jpg",
                        size: ["Single"],
                        material: ["Solid Wood"],
                        storage: ["Without Storage"],
                        price: 170,
                    },
                    {
                        heading: "Metal Stool",
                        name: "Industrial Bar Stool",
                        description: "Metal frame stool with wooden seat.",
                        image: "https://i.pinimg.com/1200x/03/29/cc/0329cc61e86bab86f44cf9170fe5373d.jpg",
                        size: ["Single"],
                        material: ["Metal", "Wood"],
                        storage: ["Without Storage"],
                        price: 140,
                    },
                ]),
            },
            kitchentable: {
                title: "Kitchen Dining Tables",
                description: "Tables for everyday kitchen dining.",
                items: padToNine([
                    {
                        heading: "Round Kitchen Table",
                        name: "Round Breakfast Table",
                        description: "Compact round breakfast table.",
                        image: "https://i.pinimg.com/1200x/08/ad/01/08ad017a44d55058c343febe07e8bb43.jpg",
                        shape: ["Round"],
                        material: ["Solid Wood"],
                        storage: ["Without Storage"],
                        price: 360,
                    },
                    {
                        heading: "Extendable Table",
                        name: "Extendable Dining Table",
                        description: "Extendable table for 4-6 seating.",
                        image: "https://i.pinimg.com/1200x/03/29/cc/0329cc61e86bab86f44cf9170fe5373d.jpg",
                        shape: ["Rectangle"],
                        material: ["Engineered Wood"],
                        storage: ["Without Storage"],
                        price: 420,
                    },
                    {
                        heading: "Counter Height Table",
                        name: "Counter Dining Table",
                        description: "Counter height table with shelves.",
                        image: "https://i.pinimg.com/1200x/71/bb/cb/71bbcb9c8561f9c9ad34dbe68982d67a.jpg",
                        shape: ["Rectangle"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 440,
                    },
                ]),
            },
            kitchenshelf: {
                title: "Kitchen Shelves",
                description: "Open shelves for pantry and display.",
                items: padToNine([
                    {
                        heading: "Open Kitchen Shelf",
                        name: "Open Shelf",
                        description: "Open wall shelf for jars and decor.",
                        image: "https://i.pinimg.com/1200x/76/dc/2e/76dc2ee8a650106fea2354ccb2beacc0.jpg",
                        size: ["Medium"],
                        material: ["Engineered Wood"],
                        storage: ["Open Storage"],
                        price: 140,
                    },
                    {
                        heading: "Metal Kitchen Shelf",
                        name: "Metal Rail Shelf",
                        description: "Metal rail shelf with hooks.",
                        image: "https://i.pinimg.com/1200x/32/01/00/3201002dff24003ec351f9879251556b.jpg",
                        size: ["Medium"],
                        material: ["Metal"],
                        storage: ["Open Storage"],
                        price: 120,
                    },
                    {
                        heading: "Corner Kitchen Shelf",
                        name: "Corner Shelf",
                        description: "Corner mounted shelf set.",
                        image: "https://i.pinimg.com/1200x/03/29/cc/0329cc61e86bab86f44cf9170fe5373d.jpg",
                        size: ["Small"],
                        material: ["Engineered Wood"],
                        storage: ["Open Storage"],
                        price: 110,
                    },
                ]),
            },
            pantryunit: {
                title: "Pantry Units",
                description: "Tall pantry units for organized storage.",
                items: padToNine([
                    {
                        heading: "Tall Pantry",
                        name: "Tall Pantry Cabinet",
                        description: "Tall cabinet with adjustable shelves.",
                        image: "https://i.pinimg.com/736x/d8/98/02/d89802713e231b4ea221148b0f92ff3d.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 520,
                    },
                    {
                        heading: "Pull-Out Pantry",
                        name: "Pull-Out Pantry",
                        description: "Pull-out pantry unit for easy access.",
                        image: "https://i.pinimg.com/1200x/76/dc/2e/76dc2ee8a650106fea2354ccb2beacc0.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 560,
                    },
                    {
                        heading: "Corner Pantry",
                        name: "Corner Pantry Cabinet",
                        description: "Corner pantry to maximize space.",
                        image: "https://i.pinimg.com/1200x/03/29/cc/0329cc61e86bab86f44cf9170fe5373d.jpg",
                        size: ["Large"],
                        material: ["Engineered Wood"],
                        storage: ["With Storage"],
                        price: 540,
                    },
                ]),
            },
        },
    },
];
